<a href="https://colab.research.google.com/github/MeherNaaz19/AIML-2025/blob/main/lab01_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

Lab01- Implement basic data structures of Numpy, Pandas, Matplotlib and Access Data from sources
Dr. Kiran Eranki
Part 01: Lab Task is implement the following data structures using Numpy and Pandas.**
Lists
Arrays
Identify their type using type()
Perform mathematical operations on these datasets created - multiplication, division, poweroff
Combine text with Numpy fuction to generate a textual output - ”Addition of Two: array1 +array 2
Implement np.sin(), log(), log2(), np.exp())
import numpy as np
lst1=[1,2,3]
array1 = np.array(lst1)
array1
array([1, 2, 3])
type(lst1)
list
type(array1)
numpy.ndarray
Perform Mathematical Operations on these datasets - Multiplication, Division, Poweroff

list2=[3,2,1]
array2=np.array(list2)
array2
array([3, 2, 1])
print("array2 multiplied by array1: ",array1*array2)
print("array2 divided by array1: ",array2/array1)
print("array2 raised to the power of array1: ",array2**array1)
print(f" {array2} raised to the power of {array1}:,{array2**array1}")
array2 multiplied by array1:  [3 4 3]
array2 divided by array1:  [3.         1.         0.33333333]
array2 raised to the power of array1:  [3 4 1]
 [3 2 1] raised to the power of [1 2 3]:,[3 4 1]
# sine function
print("Sine: ",np.sin(array1))
# logarithm
print("Natural logarithm: ",np.log(array1))
print("Base-10 logarithm: ",np.log10(array1))
print("Base-2 logarithm: ",np.log2(array1))
# Exponential
print("Exponential: ",np.exp(array1))
Sine:  [0.84147098 0.90929743 0.14112001]
Natural logarithm:  [0.         0.69314718 1.09861229]
Base-10 logarithm:  [0.         0.30103    0.47712125]
Base-2 logarithm:  [0.        1.        1.5849625]
Exponential:  [ 2.71828183  7.3890561  20.08553692]
print("Adding two numpy arrays {array1} and {array2} together:", array1+array2)
print(f"Adding two numpy arrays {array1} and {array2} together: {array1+array2}")
Part-02: Lab Task is to visualize the datasets or data using Matplotlib
builtin function Graphs
Generate Scatterplot
Let's suppose we collected age (in years), height (in cm), and weight (in kilograms) information from few patients visitng a clinic.

people = ['Ann','Brandon','Chen','David','Emily','Farook',
          'Gagan','Hamish','Imran','Julio','Katherine','Lily']
age = [21,12,32,45,37,18,28,52,5,40,48,15]
weight = [55,35,77,68,70,60,72,69,18,65,82,48]
height = [160,135,170,165,173,168,175,159,105,171,155,158]
import matplotlib.pyplot as plt
plt.scatter(weight, height)
plt.title("Relationship between Weight and Height of Patients")
plt.ylabel("Height in Meters")
plt.xlabel("Weight of Patients in Kgs")
plt.show()

Generate Bar Plot
plt.figure(figsize=(12,4))
plt.title("People's weight in kgs",fontsize=16,
          fontstyle='italic')

# Main plot function 'bar'
plt.bar(x=people,height=weight, width=0.6,
        color='orange',edgecolor='k',alpha=0.6)

plt.xlabel("People",fontsize=15)
#plt.xticks(fontsize=14,rotation=30)
#plt.yticks(fontsize=14)
plt.ylabel("Weight (in kgs)",fontsize=15)
plt.show()

Generate Histogram
import numpy as np
plt.figure(figsize=(7,5))

# Main plot function 'hist'
plt.hist(weight,color='red',edgecolor='k', alpha=0.75,bins=5)

plt.title("Histogram of patient weight",fontsize=18)
plt.xlabel("Weight in kgs",fontsize=15)
#plt.xticks(fontsize=15)
#plt.yticks(fontsize=15)
plt.show()

Part-03: Access Data from various sources and formats
import numpy as np
import pandas as pd
df1 = pd.read_table("Lab01-Text.txt")
df1
data2 = pd.read_csv("Lab01-Text.csv")
data2
data3 = pd.read_excel("Height_weight.xlsx")
data3